name: run main.py

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:    

env:
  bwcjck: ${{ secrets.BWCJCK }}
  bwcjuid: ${{ secrets.BWCJUID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python bwcj.py

